import dbmeta
# Do not edit this file, it's autogenerated


class Page:
    def __init__(self):
        dbmeta.DbMeta.init(self)

    @classmethod
    def create(cls, db, url, downloaded, status_code, pagetype, offset, length):
        anobj = cls()
        anobj.id = db.genid()
        anobj.url = url
        anobj.downloaded = downloaded
        anobj.status_code = status_code
        anobj.pagetype = pagetype
        anobj.offset = offset
        anobj.length = length
        dbmeta.DbMeta.insert(db, anobj)
        return anobj

    def update(self, db):
        return dbmeta.DbMeta.update(db, self)

    def delete(self, db):
        dbmeta.DbMeta.delete(db, self)

    @classmethod
    def get(cls, db, id):
        return dbmeta.DbMeta.get(db, cls, id)


class WaitingUrl:
    def __init__(self):
        dbmeta.DbMeta.init(self)

    @classmethod
    def create(cls, db, seqno, refcount, weight, url):
        anobj = cls()
        anobj.id = db.genid()
        anobj.seqno = seqno
        anobj.refcount = refcount
        anobj.weight = weight
        anobj.url = url
        dbmeta.DbMeta.insert(db, anobj)
        return anobj

    def update(self, db):
        return dbmeta.DbMeta.update(db, self)

    def delete(self, db):
        dbmeta.DbMeta.delete(db, self)

    @classmethod
    def get(cls, db, id):
        return dbmeta.DbMeta.get(db, cls, id)


    @classmethod
    def get_byurl(cls, db, url):
        return dbmeta.DbMeta.getby(db, cls, "url = ?", url)



def structure(db):
    db.deploypacket('www', 1, [
    "CREATE TABLE www_page (id INTEGER NOT NULL, url TEXT NOT NULL, downloaded INTEGER NOT NULL, status_code INTEGER NOT NULL, pagetype TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, PRIMARY KEY(id))",
    "CREATE TABLE www_waitinglist (id INTEGER NOT NULL, seqno INTEGER NOT NULL, refcount INTEGER NOT NULL, weight INTEGER NOT NULL, url TEXT NOT NULL, PRIMARY KEY(id))"
    ,"CREATE UNIQUE INDEX www_waitinglist_IND1 ON www_waitinglist (url)"])
    dbmeta.DbMeta.set(Page, 'www_page', ['id', 'url', 'downloaded', 'status_code', 'pagetype', 'offset', 'length'], readers={'downloaded':dbmeta.read_timestamp }, writers={'downloaded':dbmeta.write_timestamp })
    dbmeta.DbMeta.set(WaitingUrl, 'www_waitinglist', ['id', 'seqno', 'refcount', 'weight', 'url'])

