import dbmeta
# Do not edit this file, it's autogenerated


class www_page:
    def __init__(self):
        dbmeta.DbMeta.init(self)

    @classmethod
    def get(cls, db, id):
        return dbmeta.DbMeta.get(db, cls, id)

class www_waitinglist:
    def __init__(self):
        dbmeta.DbMeta.init(self)

    @classmethod
    def get(cls, db, id):
        return dbmeta.DbMeta.get(db, cls, id)


def structure(db):
    db.deploypacket('www', 1, [
    "CREATE TABLE www_page (id INTEGER NOT NULL, url TEXT NOT NULL, downloaded INTEGER NOT NULL, pagetype TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, PRIMARY KEY(id))",
    "CREATE TABLE www_waitinglist (id INTEGER NOT NULL, seqno INTEGER NOT NULL, refcount INTEGER NOT NULL, weight INTEGER NOT NULL, url TEXT NOT NULL, PRIMARY KEY(id))"])
    dbmeta.DbMeta.set(www_page, 'www_page', ['id', 'url', 'downloaded', 'pagetype', 'offset', 'length'])
    dbmeta.DbMeta.set(www_waitinglist, 'www_waitinglist', ['id', 'seqno', 'refcount', 'weight', 'url'])

